#ifndef COMMUNICATION_H
#define COMMUNICATION_H


typedef enum {
    I2C_ERROR,
    I2C_SUCCESS,
    I2C_RESET,
    I2C_HOME,
    I2C_CONFIGURATION_1,
    I2C_CONFIGURATION_2,
    I2C_CONFIGURATION_3,
    I2C_CONFIGURATION_4,
    I2C_CONFIGURATION_5,
    I2C_CONFIGURATION_6,
} I2Cmsg;


typedef enum {
    STARTUP,
    NOT_HOMED,
    CURRENTLY_HOMING,
    HOMED,
    READY,
    INITIALIZING,
    INITIALIZED,
    PHICUBE_ERROR,
} State;


typedef enum {
    CONFIGURATION_1,
    CONFIGURATION_2,
    CONFIGURATION_3,
    CONFIGURATION_4,
    CONFIGURATION_5,
    CONFIGURATION_6,
    NO_MODE,
} Mode;


#endif // COMMUNICATION_H

